version: '3'
services:
  app: 
    image: mcr.microsoft.com/devcontainers/python:1-3.12
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    # https://goledger.medium.com/reaching-hosts-localhost-from-inside-a-vscode-devcontainer-932e1c08df5c
    extra_hosts: 
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Newpassword
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: